"""empty message

Revision ID: 122c59e7bd66
Revises: 68acd1ea1434
Create Date: 2021-11-08 10:47:13.945512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122c59e7bd66'
down_revision = '68acd1ea1434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('api_key', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'user', ['api_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'api_key')
    # ### end Alembic commands ###
