"""empty message

Revision ID: 226e34d08bc5
Revises: 3ce8ce6efab7
Create Date: 2021-11-06 13:07:07.855110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226e34d08bc5'
down_revision = '3ce8ce6efab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
