"""empty message

Revision ID: 68acd1ea1434
Revises: 156fb1791c8e
Create Date: 2021-11-07 11:33:02.168431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68acd1ea1434'
down_revision = '156fb1791c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
